### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by carloslme** [carloslme/carloslme.github.io#3]
#### **Objetivo**
Permitir la creación y edición de tutoriales en la página web utilizando archivos Markdown, asegurando que estos se desplieguen correctamente y sean fáciles de gestionar en GitHub Pages. 
Esto tambien es conocido como **_Plataforma de Gestión de Contenidos (CMS)_**.

#### 1. **Configuración Inicial**
   - **Selección de plataforma**: Utilizar GitHub Pages para alojar la página web.
   - **Configuración del repositorio**: Entender la configuracion del repositorio en GitHub para el sitio web.
   - **Instalación de Jekyll**: Configurar Jekyll en el repositorio para gestionar el contenido del sitio web¹.

#### 2. **Estructura de Archivos y Directorios**
   - **Directorio de tutoriales**: Crear un directorio específico (`_tutorials`) en el repositorio para almacenar los archivos Markdown de los tutoriales.
   - **Organización de archivos**: Definir una estructura clara para organizar los archivos por categorías o temas.

#### 3. **Desarrollo de Plantilla Personalizada**
   - **Diseño de la plantilla**: Diseñar una plantilla personalizada utilizando HTML, CSS y Liquid (el lenguaje de plantillas de Jekyll).
   - **Integración de Markdown**: Asegurarse de que la plantilla pueda renderizar archivos Markdown correctamente.
   - **Estilo y formato**: Aplicar estilos CSS para asegurar una presentación coherente y atractiva de los tutoriales.

#### 4. **Parser de Markdown y Despliegue**
   - **Configuración de Jekyll**: Configurar Jekyll para que procese los archivos Markdown en el directorio `_tutorials` y los convierta en páginas HTML.
   - **Plantilla de tutoriales**: Diseñar una plantilla específica para los tutoriales que se utilizará para desplegar el contenido convertido de Markdown a HTML.
   - **Sistema de carga**: Desarrollar un flujo de trabajo que permita subir archivos Markdown al repositorio y asignarles categorías o etiquetas.

#### 5. **Integración y Pruebas**
   - **Integración del parser**: Asegurarse de que Jekyll procese y despliegue automáticamente los archivos Markdown subidos al directorio `_tutorials`.
   - **Pruebas de despliegue**: Realizar pruebas para asegurarse de que los tutoriales se desplieguen correctamente en la página web, verificando que el formato y el estilo sean consistentes.

#### 6. **Documentación y Capacitación**
   - **Guía de usuario**: Crear una guía detallada para ti y cualquier otro usuario que explique cómo crear, editar y subir archivos Markdown.
   - **Capacitación**: Si es necesario, organizar una sesión de capacitación para la familiarizacion con el proceso de creación y edición de tutoriales usando Markdown.

### Herramientas Recomendadas
- **Markdown Editors**: Visual Studio Code, Typora, Dillinger.
- **Jekyll**: Para gestionar el contenido y las plantillas en GitHub Pages.
- **GitHub Actions**: Para automatizar el despliegue del sitio web.

**Comment by carloslme** [comment]
La plantilla basica por el momento sera:
- Title
- Imagen
- Introduccion
- Indice
- Contenido
- Ejemplo
- Conclusion
- Referencias

Revisar las paginas de benchmarking: https://www.notion.so/Website-carloslme-com-d3ef723a80b0454eb4f4e6758ad26c98?pvs=4#813b0054d05e4290a2a9cc7b98c7e1fc

Este es un ejemplo sencillo de la estructura: https://github.com/carloslme/carloslme.github.io/blob/main/dummy_template.md

**Comment by laulm** [comment]
Aqui esta el url de la plantilla, si queires que haga otos ejemplos me dices 
 o igual lo puedo agregar al repositorio 
 
https://github.com/laulm/laulm.github.io/tree/main/markdown

**Comment by laulm** [comment]
Basicamente que todo sea autimatico
Renderizarlo

**Comment by carloslme** [comment]
Revisa estos links para referencias:

- https://nicolas-van.github.io/easy-markdown-to-github-pages
- https://github.com/nicolas-van (check the `_post` directory)
- https://www.youtube.com/watch?v=kzf9A9tkkl4 (Build a Blog from Scratch with Eleventy)

**Comment by laulm** [comment]
Hola hermanegro, te acabo de poner un video en slack, enseñadote todo lo que avance, nadamas dame tu opinion, si quieres que implemente alggun cambios, si es que cumplio tus expectativas y bueno cuando este eso listo voy a subirlo a tu repositorio
https://app.slack.com/client/T07KKQL8599/C07KKQNGH51

**Comment by laulm** [comment]
- [x] Organizar carpetas y los archivos de los markdown

- [x] Como desplegar un nuevo articulo / Documentacion 

- [x] Implementarlo en Github

**Comment by laulm** [comment]
Hey @carloslme 
The things I had pending are now ready:

- Organizing folders and markdown files
- How to deploy a new article / Documentation, this is already inside the ide/tutorials/README.md folder
- I have already uploaded the changes I implemented to the laulm_test branch and I have made a pull request
