### ISSUE TITLE
Modify Carlos' website

### ISSUE THREAD

**Issue by carloslme** [carloslme/carloslme.github.io#5]
#### Objetivo:
Entender el flujo de trabajo actual con la pagina de carloslme.com

#### Precedente:
Haber concluido este issue: https://github.com/carloslme/carloslme.github.io/issues/4

#### Tareas especificas:
1. Acceder al repositorio
2. Clonarlo
3. Crear una rama
4. Ejecutarlo localmente (setup, y entender como funciona el codigo existente)
5. Realizar un cambio sencillo (agregar un boton, una imagen, lo que sea).
6. Realizar un Pull Request para subir los cambios.
#### Entregable:
El cambio ha sido desplegado en la pagina https://carloslme.com/ide/

**Comment by laulm** [comment]
Listo, el nuevo cambio ha sido desplegado, he creado un boton en la seccion de  "Let's get in touch"
![Image](https://github.com/user-attachments/assets/d1faecc7-317c-467d-b401-cbe8f5beacbf)
