### ISSUE TITLE
Validate accesses

### ISSUE THREAD

**Issue by carloslme** [carloslme/carloslme.github.io#7]
Validar que se tienen accesos a los recursos para el desarrollo de la pagina:
- Figma
- GitHub repository
- GitHub Project
- Slack
- Drive folder

**Comment by carloslme** [comment]
ESte es un comentario de prueba

**Comment by laulm** [comment]
- [ YES] Figma
- [ ] GitHub repository
- [ ] GitHub Project
- [ YES] Slack
- [ YES] Drive folder

Falta acceso a GitHub

**Comment by carloslme** [comment]
Para ser que el acceso al GitHub Project es correcto, de otra forma no podrias haber escrito comentarios. 
Podrias revisar nuevamente tu correo electronico para el acceso al repositorio?
-> https://github.com/carloslme/carloslme.github.io

**Comment by laulm** [comment]
Ya tengo los accesos, gracias
